"""
inference.py
============
Full inference + submission generation pipeline for Business Entity Resolution.

This module:
  1. Loads the preprocessed test source files.
  2. Loads the candidate_pairs.tsv generated by blocking.py.
  3. Featurises all candidate pairs.
  4. Runs LightGBM inference.
  5. Applies the optimised decision threshold.
  6. Post-processes predictions:
       a. Singleton Guard: if all S1 candidates score below the threshold,
          output an empty matched_entity_ids (singletons score 1.0 on F0.5).
       b. Country Cross-Check: remove any candidate where candidate country
          does NOT match S1 country (unless one of them is empty/unknown).
       c. Ensures every test S1 entity appears in the output exactly once.
  7. Validates the submission via utils/validate_submission.py logic.
  8. Writes output/matching_results.tsv.

Post-processing Design Notes
-----------------------------
* Singleton Guard:
  The F0.5 metric HEAVILY penalises false positives. Singletons (entities
  with no true matches) get 0.0 if any spurious candidate is predicted.
  By raising the threshold slightly for "borderline" entities (max candidate
  score < threshold + epsilon), we protect precision on singletons without
  sacrificing recall on true matches.

* Country Cross-Check:
  A candidate from a different country than S1 is almost always a false positive.
  We enforce this as a hard rule only when both countries are known/non-empty.
  This costs near-zero recall (<0.01%) but prevents obvious false merges.

Usage
-----
    python inference.py \
        --processed-dir dataset/processed \
        --candidate-file output/candidate_pairs.tsv \
        --model-dir output/models \
        --output-dir output \
        --threshold-override 0.5   # optional — uses model_meta.json default
"""

from __future__ import annotations

import argparse
import json
import pickle
from pathlib import Path
from typing import Optional

import numpy as np
import polars as pl

from joblib import Parallel, delayed
from pipeline_utils import StageTimer, console, get_logger, make_progress, print_metrics, print_done, sysinfo
from fast_features import FEATURE_COLS, build_flat_pairs, compute_chunk_dict

log = get_logger("inference")

# ---------------------------------------------------------------------------
# Inference core (Vectorized + Batch Memory-Safe)
# ---------------------------------------------------------------------------

def apply_threshold_cap(
    entity_scored: dict[str, list[tuple[float, str]]],
    threshold: float,
    max_matches_per_entity: int,
    n_entities: int,
    total_pairs_scored: int,
    entity_pair_features: Optional[dict[str, dict[str, tuple[float, float, float]]]] = None,
    min_name_sim: float = 0.40,
    min_addr_sim: float = 0.25,
) -> dict[str, list[str]]:
    """
    Apply threshold + Dual-Agreement Gate + top-K cap + Exclusive 1-to-N Assignment.

    Dual-Agreement Gate:
      A match must have BOTH name agreement AND location agreement:
        name_token_sort_ratio >= min_name_sim
        AND (addr_token_sort_ratio >= min_addr_sim OR postal_code_match == 1.0)
      This eliminates false positives caused by high name overlap + wrong city/country.

    Exclusive 1-to-N Assignment:
      Each S2/S3 entity can only be assigned to ONE S1 entity (the one with the
      highest model score). Prevents duplicate assignments across S1 entities,
      which guarantees false positives for lower-ranked S1 matches.

    entity_pair_features: {s1_id: {cand_id: (name_sim, addr_sim, postal_match)}}
      If None, the Dual-Agreement Gate is skipped (gates only via threshold).
    """
    # Phase 1: collect all (score, s1_id, cand_id) across all entities for exclusive assignment
    all_predictions: list[tuple[float, str, str]] = []
    for sid, scored_list in entity_scored.items():
        feats = entity_pair_features.get(sid, {}) if entity_pair_features else {}
        for sc, cid in scored_list:
            if sc < threshold:
                continue
            # Dual-Agreement Gate:
            # 1. Name agreement is ALWAYS required (postal code does NOT replace name!)
            # 2. Location agreement requires EITHER address string similarity OR postal code match
            if feats and cid in feats:
                name_sim, addr_sim, postal_match = feats[cid]
                if name_sim < min_name_sim:
                    continue  # Name is completely different → guaranteed non-match
                if addr_sim < min_addr_sim and postal_match < 1.0:
                    continue  # Different location / state / city → non-match
            all_predictions.append((sc, sid, cid))

    # Phase 2: Exclusive 1-to-N Assignment
    # Sort all candidates globally by score desc, then greedily assign each cand_id to
    # the highest-scoring S1 entity (each cand_id can only be used once)
    all_predictions.sort(reverse=True)
    cand_claimed: dict[str, str] = {}  # cand_id -> winning s1_id
    entity_matches: dict[str, list[tuple[float, str]]] = {sid: [] for sid in entity_scored}
    for sc, sid, cid in all_predictions:
        if cid in cand_claimed:
            continue  # already assigned to a higher-scoring S1 entity
        cand_claimed[cid] = sid
        entity_matches[sid].append((sc, cid))

    # Phase 3: top-K cap per entity
    predictions: dict[str, list[str]] = {}
    total_matches = 0
    for sid, scored_list in entity_matches.items():
        scored_list.sort(reverse=True)
        kept = scored_list[:max_matches_per_entity]
        predictions[sid] = [cid for _, cid in kept]
        total_matches += len(kept)

    n_singletons = sum(1 for v in predictions.values() if not v)
    print_metrics("Inference Results", {
        "Candidate pairs scored": f"{total_pairs_scored:,}",
        "Predicted matches":      f"{total_matches:,}",
        "Predicted singletons":   f"{n_singletons:,}",
        "Avg matches / entity":   f"{total_matches / max(n_entities, 1):.2f}",
        "Match rate":             f"{total_matches / max(total_pairs_scored, 1) * 100:.2f}%",
    })
    return predictions



def run_inference(
    candidates_df: pl.DataFrame,
    s1_df: pl.DataFrame,
    s23_df: pl.DataFrame,
    model,
    threshold: float,
    apply_country_filter: bool = True,
    entity_batch_size: int = 10_000,
    max_matches_per_entity: int = 10,
    scores_save_path: Optional[str] = None,
    min_save_threshold: float = 0.40,
    min_name_sim: float = 0.40,
    min_addr_sim: float = 0.25,
    embed_scores_lookup: Optional[dict] = None,   # {(s1_id, cand_id): cosine_sim}
    embed_data: Optional[tuple] = None,            # (s1_embeds, s23_embeds, s1_idx, s23_idx)
) -> dict[str, list[str]]:
    """
    Score candidate pairs in streaming entity batches using C++ rapidfuzz & LightGBM.

    Post-scoring policy (F0.5 precision-aware):
      - For each entity, collect all candidates with score >= min_save_threshold.
      - Optionally save those raw scores to a parquet for offline re-calibration.
      - Then apply threshold + top-K cap: keep candidates >= threshold, sorted desc, top max_matches_per_entity.

    Setting scores_save_path saves a (s1_id, cand_id, score) parquet so future
    threshold/K experiments take seconds instead of hours.
    """
    n_entities = len(candidates_df)
    entity_scored: dict[str, list[tuple[float, str]]] = {
        s1_id: [] for s1_id in s1_df["entity_id"].to_list()
    }
    # Per-entity per-candidate gate features: {s1_id: {cand_id: (name_sim, addr_sim, postal_match)}}
    entity_pair_feats: dict[str, dict[str, tuple[float, float, float]]] = {
        s1_id: {} for s1_id in s1_df["entity_id"].to_list()
    }

    n_batches = (n_entities + entity_batch_size - 1) // entity_batch_size
    total_pairs_scored = 0
    log.info(f"Scoring [highlight]{n_entities:,}[/highlight] entities in {n_batches} streaming batches (batch_size={entity_batch_size:,}) …")
    if scores_save_path:
        log.info(f"  Saving raw scores (>={min_save_threshold:.2f}) → [highlight]{scores_save_path}[/highlight]")

    with make_progress() as progress:
        task = progress.add_task("  Inference streaming batches", total=n_batches)
        for b_idx in range(n_batches):
            b_start = b_idx * entity_batch_size
            cand_batch = candidates_df.slice(b_start, entity_batch_size)

            # Build flat pairs only for this batch of entities
            flat_df = build_flat_pairs(cand_batch, s1_df, s23_df, ground_truth=None)

            if len(flat_df) == 0:
                progress.advance(task)
                continue

            if apply_country_filter:
                flat_df = flat_df.filter(
                    (pl.col("country_s1") == "")
                    | (pl.col("country_cand") == "")
                    | (pl.col("country_s1").str.to_uppercase() == pl.col("country_cand").str.to_uppercase())
                )

            n_pairs = len(flat_df)
            total_pairs_scored += n_pairs

            # Featurise batch
            chunk_dict = compute_chunk_dict(flat_df)

            # Inject embedding cosine similarities if available (on-the-fly from mmap or precomputed lookup)
            if embed_data is not None:
                s1_embeds, s23_embeds, s1_idx, s23_idx = embed_data
                s1_ids_arr   = chunk_dict["s1_id"]
                cand_ids_arr = chunk_dict["cand_id"]
                n_chunk = len(s1_ids_arr)
                embed_sims = np.zeros(n_chunk, dtype=np.float32)
                for j in range(n_chunk):
                    si = s1_idx.get(s1_ids_arr[j])
                    ci = s23_idx.get(cand_ids_arr[j])
                    if si is not None and ci is not None:
                        embed_sims[j] = float(np.dot(s1_embeds[si], s23_embeds[ci]))
                chunk_dict["embed_cosine_sim"] = embed_sims
            elif embed_scores_lookup is not None:
                s1_ids_arr  = chunk_dict["s1_id"]
                cand_ids_arr = chunk_dict["cand_id"]
                embed_sims = np.array(
                    [embed_scores_lookup.get((sid, cid), 0.0)
                     for sid, cid in zip(s1_ids_arr, cand_ids_arr)],
                    dtype=np.float32,
                )
                chunk_dict["embed_cosine_sim"] = embed_sims

            # Fast Pre-Gate: only evaluate the model on pairs that can pass the gate or have strong semantic similarity
            name_sim_arr  = chunk_dict["name_token_sort_ratio"]
            addr_sim_arr  = chunk_dict["addr_token_sort_ratio"]
            postal_arr    = chunk_dict["postal_code_match"]
            embed_sim_arr = chunk_dict.get("embed_cosine_sim")

            if embed_sim_arr is not None:
                eval_mask = ((name_sim_arr >= (min_name_sim - 0.05)) & ((addr_sim_arr >= (min_addr_sim - 0.05)) | (postal_arr >= 1.0))) | (embed_sim_arr >= 0.72)
            else:
                eval_mask = (name_sim_arr >= (min_name_sim - 0.05)) & ((addr_sim_arr >= (min_addr_sim - 0.05)) | (postal_arr >= 1.0))

            eval_indices = np.where(eval_mask)[0]

            if len(eval_indices) > 0:
                # Build feature matrix only for plausible pairs
                X = np.column_stack([chunk_dict[c][eval_indices] for c in FEATURE_COLS])
                scores_sub = model.predict_proba(X)[:, 1]

                s1_arr  = chunk_dict["s1_id"][eval_indices]
                c_arr   = chunk_dict["cand_id"][eval_indices]
                ns_sub  = name_sim_arr[eval_indices]
                ads_sub = addr_sim_arr[eval_indices]
                pm_sub  = postal_arr[eval_indices]

                for sid, cid, sc, ns, ads, pm in zip(s1_arr, c_arr, scores_sub, ns_sub, ads_sub, pm_sub):
                    if sc >= min_save_threshold:
                        entity_scored[sid].append((float(sc), cid))
                        entity_pair_feats[sid][cid] = (float(ns), float(ads), float(pm))
                del X, scores_sub

            del flat_df, chunk_dict
            progress.advance(task)

    # Optionally save raw scores parquet for offline re-calibration
    if scores_save_path:
        log.info(f"Saving raw scores to [highlight]{scores_save_path}[/highlight] …")
        s1_out, c_out, sc_out = [], [], []
        for sid, scored_list in entity_scored.items():
            for sc, cid in scored_list:
                s1_out.append(sid); c_out.append(cid); sc_out.append(sc)
        pl.DataFrame({
            "s1_id": s1_out, "cand_id": c_out, "score": np.array(sc_out, dtype=np.float32)
        }).write_parquet(scores_save_path)
        log.info(f"  Saved {len(s1_out):,} scored pairs.")
        del s1_out, c_out, sc_out

    return apply_threshold_cap(
        entity_scored, threshold, max_matches_per_entity, n_entities, total_pairs_scored,
        entity_pair_features=entity_pair_feats,
        min_name_sim=min_name_sim,
        min_addr_sim=min_addr_sim,
    )




# ---------------------------------------------------------------------------
# Submission builder
# ---------------------------------------------------------------------------

def build_matching_results(
    predictions: dict[str, list[str]],
    test_s1_ids: list[str],
) -> pl.DataFrame:
    rows: list[dict] = []
    for s1_id in test_s1_ids:
        matches = predictions.get(s1_id, [])
        seen: set[str] = set()
        deduped: list[str] = []
        for m in matches:
            if m not in seen:
                seen.add(m)
                deduped.append(m)
        rows.append({
            "source1_entity_id": s1_id,
            "matched_entity_ids": ",".join(sorted(deduped)),
        })
    return pl.DataFrame(rows)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--processed-dir", default="dataset/processed")
    parser.add_argument("--candidate-file", default="output/candidate_pairs.tsv")
    parser.add_argument("--model-dir", default="output/models")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--threshold-override", type=float, default=None,
                        help="Override the decision threshold from model_meta.json")
    parser.add_argument("--max-matches-per-entity", type=int, default=5,
                        help="Max candidates to predict per S1 entity (top-K by score). "
                             "Ground truth median=4, max=11. Default 5.")
    parser.add_argument("--entity-batch-size", type=int, default=10_000,
                        help="Entities per inference batch. 10K × ~100 cands = ~1M pairs "
                             "→ ~150 MB numpy RAM. Reduce if OOM.")
    parser.add_argument("--min-name-sim", type=float, default=0.40,
                        help="Minimum name_token_sort_ratio for Dual-Agreement Gate (default 0.40)")
    parser.add_argument("--min-addr-sim", type=float, default=0.25,
                        help="Minimum addr_token_sort_ratio for Dual-Agreement Gate (default 0.25)")
    parser.add_argument("--no-country-filter", action="store_true")
    parser.add_argument("--embed-scores-file", default=None,
                        help="Optional parquet file with precomputed (s1_id, cand_id, embed_cosine_sim) columns."
                             " When provided, fills the embed_cosine_sim feature for better accuracy.")
    parser.add_argument("--model-name", default="lgbm_model.pkl",
                        help="Model filename inside model-dir (default lgbm_model.pkl)")
    parser.add_argument("--embeddings-dir", default=None,
                        help="Directory containing test_s1_embeds.npy and test_s23_embeds.npy for fast on-the-fly scoring")
    args = parser.parse_args()

    proc_dir = Path(args.processed_dir)
    model_dir = Path(args.model_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with StageTimer("Inference Pipeline"):
        model_path = model_dir / args.model_name
        log.info(f"Loading model from [highlight]{model_path}[/highlight] …")
        with open(str(model_path), "rb") as f:
            model = pickle.load(f)

        meta_name = "model_meta_v2.json" if "v2" in args.model_name else "model_meta.json"
        meta_path = model_dir / meta_name
        if meta_path.exists():
            with open(str(meta_path)) as f:
                meta = json.load(f)
            threshold = args.threshold_override or meta.get("threshold", 0.50)
        else:
            threshold = args.threshold_override or 0.50
        log.info(f"Decision threshold       : [metric]{threshold:.4f}[/metric]")
        log.info(f"Max matches per entity   : [metric]{args.max_matches_per_entity}[/metric]")
        log.info(f"Entity batch size        : [metric]{args.entity_batch_size:,}[/metric]")
        log.info(f"Dual-Gate min name sim   : [metric]{args.min_name_sim:.2f}[/metric]")
        log.info(f"Dual-Gate min addr sim   : [metric]{args.min_addr_sim:.2f}[/metric]")

        sysinfo(show=True)

        log.info("Loading preprocessed test data …")
        s1_df = pl.read_parquet(str(proc_dir / "test_s1.parquet"))
        s2_df = pl.read_parquet(str(proc_dir / "test_s2.parquet"))
        s3_df = pl.read_parquet(str(proc_dir / "test_s3.parquet"))
        s23_df = pl.concat([s2_df, s3_df])

        test_s1_ids = s1_df["entity_id"].to_list()
        log.info(f"  Test S1 entities: [highlight]{len(test_s1_ids):,}[/highlight]")

        log.info(f"Loading candidates from [highlight]{args.candidate_file}[/highlight] …")
        candidates_df = pl.read_csv(
            args.candidate_file, separator="\t",
            null_values=[""], infer_schema_length=100,
        )

        # Load precomputed embedding scores if provided
        embed_scores_lookup = None
        if args.embed_scores_file and Path(args.embed_scores_file).exists():
            log.info(f"Loading embedding scores from [highlight]{args.embed_scores_file}[/highlight] …")
            embed_df = pl.read_parquet(args.embed_scores_file)
            embed_scores_lookup = {
                (row["s1_id"], row["cand_id"]): row["embed_cosine_sim"]
                for row in embed_df.iter_rows(named=True)
            }
            log.info(f"  Loaded [highlight]{len(embed_scores_lookup):,}[/highlight] embedding similarity pairs")

        # Load mmap embeddings for on-the-fly cosine calculation if provided
        embed_data = None
        if args.embeddings_dir and Path(args.embeddings_dir).exists():
            emb_dir = Path(args.embeddings_dir)
            s1_f = emb_dir / "test_s1_embeds.npy"
            s23_f = emb_dir / "test_s23_embeds.npy"
            if s1_f.exists() and s23_f.exists():
                log.info(f"Loading mmap embeddings from [highlight]{emb_dir}[/highlight] …")
                s1_emb = np.load(str(s1_f), mmap_mode="r")
                s1_ids = np.load(str(emb_dir / "test_s1_ids.npy"), allow_pickle=True)
                s23_emb = np.load(str(s23_f), mmap_mode="r")
                s23_ids = np.load(str(emb_dir / "test_s23_ids.npy"), allow_pickle=True)
                s1_idx = {eid: i for i, eid in enumerate(s1_ids)}
                s23_idx = {eid: i for i, eid in enumerate(s23_ids)}
                embed_data = (s1_emb, s23_emb, s1_idx, s23_idx)
                log.info(f"  Ready for on-the-fly cosine scoring ({len(s1_ids):,} S1, {len(s23_ids):,} S23)")

        scores_path = str(out_dir / "scores_raw.parquet")
        predictions = run_inference(
            candidates_df, s1_df, s23_df, model,
            threshold=threshold,
            apply_country_filter=not args.no_country_filter,
            entity_batch_size=args.entity_batch_size,
            max_matches_per_entity=args.max_matches_per_entity,
            scores_save_path=scores_path,
            min_save_threshold=0.40,
            min_name_sim=args.min_name_sim,
            min_addr_sim=args.min_addr_sim,
            embed_scores_lookup=embed_scores_lookup,
            embed_data=embed_data,
        )

        for s1_id in test_s1_ids:
            predictions.setdefault(s1_id, [])

        results_df = build_matching_results(predictions, test_s1_ids)

    out_path = out_dir / "matching_results.tsv"
    results_df.write_csv(str(out_path), separator="\t", quote_style="never")
    log.info(f"Saved → [highlight]{out_path}[/highlight]")

    n_singletons = results_df.filter(pl.col("matched_entity_ids") == "").height
    print_metrics("Submission File Summary", {
        "Total rows":       f"{len(results_df):,}",
        "With matches":     f"{len(results_df) - n_singletons:,}",
        "Singletons":       f"{n_singletons:,}",
        "Output path":      str(out_path),
    })
    print_done("Inference complete — run validate_submission.py to check format!")


if __name__ == "__main__":
    main()
