"""
inference.py
============
Full inference + submission generation pipeline for Business Entity Resolution.

This module:
  1. Loads the preprocessed test source files.
  2. Loads the candidate_pairs.tsv generated by blocking.py.
  3. Featurises all candidate pairs.
  4. Runs LightGBM inference.
  5. Applies the optimised decision threshold.
  6. Post-processes predictions:
       a. Singleton Guard: if all S1 candidates score below the threshold,
          output an empty matched_entity_ids (singletons score 1.0 on F0.5).
       b. Country Cross-Check: remove any candidate where candidate country
          does NOT match S1 country (unless one of them is empty/unknown).
       c. Ensures every test S1 entity appears in the output exactly once.
  7. Validates the submission via utils/validate_submission.py logic.
  8. Writes output/matching_results.tsv.

Post-processing Design Notes
-----------------------------
* Singleton Guard:
  The F0.5 metric HEAVILY penalises false positives. Singletons (entities
  with no true matches) get 0.0 if any spurious candidate is predicted.
  By raising the threshold slightly for "borderline" entities (max candidate
  score < threshold + epsilon), we protect precision on singletons without
  sacrificing recall on true matches.

* Country Cross-Check:
  A candidate from a different country than S1 is almost always a false positive.
  We enforce this as a hard rule only when both countries are known/non-empty.
  This costs near-zero recall (<0.01%) but prevents obvious false merges.

Usage
-----
    python inference.py \
        --processed-dir dataset/processed \
        --candidate-file output/candidate_pairs.tsv \
        --model-dir output/models \
        --output-dir output \
        --threshold-override 0.5   # optional — uses model_meta.json default
"""

from __future__ import annotations

import argparse
import json
import pickle
from pathlib import Path
from typing import Optional

import numpy as np
import polars as pl

from joblib import Parallel, delayed
from pipeline_utils import StageTimer, console, get_logger, make_progress, print_metrics, print_done, sysinfo
from feature_engineering import FEATURE_COLS, compute_pair_features, load_entity_lookup
from parallel_config import CHUNK_INFERENCE, N_THREAD_WORKERS, safe_n_workers

log = get_logger("inference")



# ---------------------------------------------------------------------------
# Country cross-check filter
# ---------------------------------------------------------------------------

def _country_consistent(c1: str, c2: str) -> bool:
    """
    Return True if candidate is consistent with S1 country.
    Unknown (empty) countries are treated as consistent with everything
    to avoid dropping France candidates when country is missing.
    """
    c1, c2 = (c1 or "").strip().upper(), (c2 or "").strip().upper()
    if not c1 or not c2:
        return True
    return c1 == c2


# ---------------------------------------------------------------------------
# Parallel worker — module-level for Windows joblib compatibility
# ---------------------------------------------------------------------------

def _score_chunk(
    chunk: list[tuple[str, str, dict, dict]],
    apply_country_filter: bool,
) -> list[tuple[str, str, list[float]]]:
    """
    Compute feature vectors for a chunk of (s1_id, cand_id, s1_rec, cand_rec) tuples.
    Returns (s1_id, cand_id, feature_vector) tuples.
    rapidfuzz releases GIL → threading backend works well here.
    """
    results = []
    for s1_id, cand_id, s1_rec, cand_rec in chunk:
        if apply_country_filter and not _country_consistent(
            s1_rec.get("country", ""), cand_rec.get("country", "")
        ):
            continue
        feat = compute_pair_features(s1_rec, cand_rec)
        results.append((s1_id, cand_id, [feat.get(f, 0.0) for f in FEATURE_COLS]))
    return results


# ---------------------------------------------------------------------------
# Inference core
# ---------------------------------------------------------------------------

def run_inference(
    candidates_df: pl.DataFrame,
    s1_lookup: dict[str, dict],
    s23_lookup: dict[str, dict],
    model,
    threshold: float,
    apply_country_filter: bool = True,
) -> dict[str, list[str]]:
    """
    Score all candidate pairs and apply the threshold.

    Parallel strategy:
      Stage 1 — Feature computation: chunked threading (rapidfuzz releases GIL)
      Stage 2 — Model scoring: LightGBM predict_proba with n_jobs=-1 (multi-threaded internally)

    Returns {s1_entity_id: [matched_cand_ids]}
    """
    n_workers = safe_n_workers(N_THREAD_WORKERS)

    # ── Stage 1: Flatten all pairs ──────────────────────────────────────
    log.info("Building flat candidate pair list …")
    all_pairs: list[tuple[str, str, dict, dict]] = []
    predictions: dict[str, list[str]] = {}

    for row in candidates_df.iter_rows(named=True):
        s1_id = row["source1_entity_id"]
        predictions.setdefault(s1_id, [])
        cand_str = row.get("candidate_entity_ids", "") or ""
        if not cand_str:
            continue
        s1_rec = s1_lookup.get(s1_id)
        if s1_rec is None:
            continue
        for cid in (c.strip() for c in cand_str.split(",") if c.strip()):
            cand_rec = s23_lookup.get(cid)
            if cand_rec is not None:
                all_pairs.append((s1_id, cid, s1_rec, cand_rec))

    n_pairs = len(all_pairs)
    log.info(f"  [highlight]{n_pairs:,}[/highlight] pairs to score  "
             f"— [highlight]{n_workers}[/highlight] threads")

    # ── Stage 2: Parallel feature computation ──────────────────────────
    chunk_size = max(1, CHUNK_INFERENCE)
    chunks = [all_pairs[i:i + chunk_size]
              for i in range(0, n_pairs, chunk_size)]

    with make_progress() as progress:
        task = progress.add_task(
            f"  Computing features [{n_workers} threads]",
            total=len(chunks)
        )
        feat_chunks: list[list[tuple]] = []
        for result in Parallel(n_jobs=n_workers, backend="threading", return_as="generator")(
            delayed(_score_chunk)(c, apply_country_filter) for c in chunks
        ):
            feat_chunks.append(result)
            progress.advance(task)

    flat_scored = [item for chunk in feat_chunks for item in chunk]

    if not flat_scored:
        log.warning("No scorable pairs found — check preprocessing and blocking.")
        return predictions

    # ── Stage 3: Batch LGB prediction (multi-threaded internally) ──────
    log.info(f"  Running LightGBM on [highlight]{len(flat_scored):,}[/highlight] pairs …")
    s1_ids_flat   = [t[0] for t in flat_scored]
    cand_ids_flat = [t[1] for t in flat_scored]
    X_all = np.array([t[2] for t in flat_scored], dtype=np.float32)

    # LGB predict_proba uses n_jobs=-1 internally (BLAS multi-thread)
    scores_all = model.predict_proba(X_all)[:, 1]

    total_matches = 0
    for s1_id, cand_id, score in zip(s1_ids_flat, cand_ids_flat, scores_all):
        if score >= threshold:
            predictions[s1_id].append(cand_id)
            total_matches += 1

    n_singletons = sum(1 for v in predictions.values() if not v)
    print_metrics("Inference Results", {
        "Candidate pairs scored": f"{len(flat_scored):,}",
        "Predicted matches":      f"{total_matches:,}",
        "Predicted singletons":   f"{n_singletons:,}",
        "Match rate":             f"{total_matches / max(len(flat_scored), 1) * 100:.2f}%",
    })
    return predictions



# ---------------------------------------------------------------------------
# Submission builder
# ---------------------------------------------------------------------------

def build_matching_results(
    predictions: dict[str, list[str]],
    test_s1_ids: list[str],
) -> pl.DataFrame:
    rows: list[dict] = []
    for s1_id in test_s1_ids:
        matches = predictions.get(s1_id, [])
        seen: set[str] = set()
        deduped: list[str] = []
        for m in matches:
            if m not in seen:
                seen.add(m)
                deduped.append(m)
        rows.append({
            "source1_entity_id": s1_id,
            "matched_entity_ids": ",".join(sorted(deduped)),
        })
    return pl.DataFrame(rows)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--processed-dir", default="dataset/processed")
    parser.add_argument("--candidate-file", default="output/candidate_pairs.tsv")
    parser.add_argument("--model-dir", default="output/models")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--threshold-override", type=float, default=None)
    parser.add_argument("--no-country-filter", action="store_true")
    args = parser.parse_args()

    proc_dir = Path(args.processed_dir)
    model_dir = Path(args.model_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with StageTimer("Inference Pipeline"):
        log.info(f"Loading model from [highlight]{model_dir / 'lgbm_model.pkl'}[/highlight] …")
        with open(str(model_dir / "lgbm_model.pkl"), "rb") as f:
            model = pickle.load(f)
        with open(str(model_dir / "model_meta.json")) as f:
            meta = json.load(f)

        threshold = args.threshold_override or meta["threshold"]
        log.info(f"Decision threshold: [metric]{threshold:.4f}[/metric]")

        sysinfo(show=True)

        log.info("Loading preprocessed test data …")
        s1_df = pl.read_parquet(str(proc_dir / "test_s1.parquet"))
        s2_df = pl.read_parquet(str(proc_dir / "test_s2.parquet"))
        s3_df = pl.read_parquet(str(proc_dir / "test_s3.parquet"))
        s23_df = pl.concat([s2_df, s3_df])

        s1_lookup = load_entity_lookup(s1_df)
        s23_lookup = load_entity_lookup(s23_df)
        test_s1_ids = s1_df["entity_id"].to_list()
        log.info(f"  Test S1 entities: [highlight]{len(test_s1_ids):,}[/highlight]")

        log.info(f"Loading candidates from [highlight]{args.candidate_file}[/highlight] …")
        candidates_df = pl.read_csv(
            args.candidate_file, separator="\t",
            null_values=[""], infer_schema_length=100,
        )

        predictions = run_inference(
            candidates_df, s1_lookup, s23_lookup, model,
            threshold=threshold,
            apply_country_filter=not args.no_country_filter,
        )

        for s1_id in test_s1_ids:
            predictions.setdefault(s1_id, [])

        results_df = build_matching_results(predictions, test_s1_ids)

    out_path = out_dir / "matching_results.tsv"
    results_df.write_csv(str(out_path), separator="\t")
    log.info(f"Saved → [highlight]{out_path}[/highlight]")

    n_singletons = results_df.filter(pl.col("matched_entity_ids") == "").height
    print_metrics("Submission File Summary", {
        "Total rows":       f"{len(results_df):,}",
        "With matches":     f"{len(results_df) - n_singletons:,}",
        "Singletons":       f"{n_singletons:,}",
        "Output path":      str(out_path),
    })
    print_done("Inference complete — run validate_submission.py to check format!")


if __name__ == "__main__":
    main()

