"""
inference.py
============
Full inference + submission generation pipeline for Business Entity Resolution.

This module:
  1. Loads the preprocessed test source files.
  2. Loads the candidate_pairs.tsv generated by blocking.py.
  3. Featurises all candidate pairs.
  4. Runs LightGBM inference.
  5. Applies the optimised decision threshold.
  6. Post-processes predictions:
       a. Singleton Guard: if all S1 candidates score below the threshold,
          output an empty matched_entity_ids (singletons score 1.0 on F0.5).
       b. Country Cross-Check: remove any candidate where candidate country
          does NOT match S1 country (unless one of them is empty/unknown).
       c. Ensures every test S1 entity appears in the output exactly once.
  7. Validates the submission via utils/validate_submission.py logic.
  8. Writes output/matching_results.tsv.

Post-processing Design Notes
-----------------------------
* Singleton Guard:
  The F0.5 metric HEAVILY penalises false positives. Singletons (entities
  with no true matches) get 0.0 if any spurious candidate is predicted.
  By raising the threshold slightly for "borderline" entities (max candidate
  score < threshold + epsilon), we protect precision on singletons without
  sacrificing recall on true matches.

* Country Cross-Check:
  A candidate from a different country than S1 is almost always a false positive.
  We enforce this as a hard rule only when both countries are known/non-empty.
  This costs near-zero recall (<0.01%) but prevents obvious false merges.

Usage
-----
    python inference.py \
        --processed-dir dataset/processed \
        --candidate-file output/candidate_pairs.tsv \
        --model-dir output/models \
        --output-dir output \
        --threshold-override 0.5   # optional — uses model_meta.json default
"""

from __future__ import annotations

import argparse
import json
import pickle
from pathlib import Path
from typing import Optional

import numpy as np
import polars as pl

from joblib import Parallel, delayed
from pipeline_utils import StageTimer, console, get_logger, make_progress, print_metrics, print_done, sysinfo
from fast_features import FEATURE_COLS, build_flat_pairs, compute_chunk_dict

log = get_logger("inference")

# ---------------------------------------------------------------------------
# Inference core (Vectorized + Batch Memory-Safe)
# ---------------------------------------------------------------------------

def apply_threshold_cap(
    entity_scored: dict[str, list[tuple[float, str]]],
    threshold: float,
    max_matches_per_entity: int,
    n_entities: int,
    total_pairs_scored: int,
) -> dict[str, list[str]]:
    """Apply threshold + top-K cap to per-entity score lists. Used both inline and for reprocessing saved scores."""
    predictions: dict[str, list[str]] = {}
    total_matches = 0
    for sid, scored_list in entity_scored.items():
        above = [(sc, cid) for sc, cid in scored_list if sc >= threshold]
        if not above:
            predictions[sid] = []
        else:
            above.sort(reverse=True)
            kept = above[:max_matches_per_entity]
            predictions[sid] = [cid for _, cid in kept]
            total_matches += len(kept)

    n_singletons = sum(1 for v in predictions.values() if not v)
    print_metrics("Inference Results", {
        "Candidate pairs scored": f"{total_pairs_scored:,}",
        "Predicted matches":      f"{total_matches:,}",
        "Predicted singletons":   f"{n_singletons:,}",
        "Avg matches / entity":   f"{total_matches / max(n_entities, 1):.2f}",
        "Match rate":             f"{total_matches / max(total_pairs_scored, 1) * 100:.2f}%",
    })
    return predictions


def run_inference(
    candidates_df: pl.DataFrame,
    s1_df: pl.DataFrame,
    s23_df: pl.DataFrame,
    model,
    threshold: float,
    apply_country_filter: bool = True,
    entity_batch_size: int = 10_000,
    max_matches_per_entity: int = 10,
    scores_save_path: Optional[str] = None,
    min_save_threshold: float = 0.40,
) -> dict[str, list[str]]:
    """
    Score candidate pairs in streaming entity batches using C++ rapidfuzz & LightGBM.

    Post-scoring policy (F0.5 precision-aware):
      - For each entity, collect all candidates with score >= min_save_threshold.
      - Optionally save those raw scores to a parquet for offline re-calibration.
      - Then apply threshold + top-K cap: keep candidates >= threshold, sorted desc, top max_matches_per_entity.

    Setting scores_save_path saves a (s1_id, cand_id, score) parquet so future
    threshold/K experiments take seconds instead of hours.
    """
    n_entities = len(candidates_df)
    # Initialize accumulator from s1_df (small, already loaded) — NOT from the
    # giant 2.27 GB candidates_df which would OOM on .to_list()
    entity_scored: dict[str, list[tuple[float, str]]] = {
        s1_id: [] for s1_id in s1_df["entity_id"].to_list()
    }

    n_batches = (n_entities + entity_batch_size - 1) // entity_batch_size
    total_pairs_scored = 0
    log.info(f"Scoring [highlight]{n_entities:,}[/highlight] entities in {n_batches} streaming batches (batch_size={entity_batch_size:,}) …")
    if scores_save_path:
        log.info(f"  Saving raw scores (>={min_save_threshold:.2f}) → [highlight]{scores_save_path}[/highlight]")

    with make_progress() as progress:
        task = progress.add_task("  Inference streaming batches", total=n_batches)
        for b_idx in range(n_batches):
            b_start = b_idx * entity_batch_size
            cand_batch = candidates_df.slice(b_start, entity_batch_size)

            # Build flat pairs only for this batch of entities
            flat_df = build_flat_pairs(cand_batch, s1_df, s23_df, ground_truth=None)

            if len(flat_df) == 0:
                progress.advance(task)
                continue

            if apply_country_filter:
                flat_df = flat_df.filter(
                    (pl.col("country_s1") == "")
                    | (pl.col("country_cand") == "")
                    | (pl.col("country_s1").str.to_uppercase() == pl.col("country_cand").str.to_uppercase())
                )

            n_pairs = len(flat_df)
            total_pairs_scored += n_pairs

            # Featurise batch
            chunk_dict = compute_chunk_dict(flat_df)

            # Build feature matrix in FEATURE_COLS order
            X = np.column_stack([chunk_dict[c] for c in FEATURE_COLS])

            # Model prediction — scores in [0, 1]
            scores = model.predict_proba(X)[:, 1]

            # Accumulate per-entity (score, cand_id) for candidates above min_save_threshold
            s1_arr = chunk_dict["s1_id"]
            c_arr  = chunk_dict["cand_id"]
            for sid, cid, sc in zip(s1_arr, c_arr, scores):
                if sc >= min_save_threshold:
                    entity_scored[sid].append((float(sc), cid))

            del flat_df, chunk_dict, X, scores
            progress.advance(task)

    # Optionally save raw scores parquet for offline re-calibration
    if scores_save_path:
        log.info(f"Saving raw scores to [highlight]{scores_save_path}[/highlight] …")
        s1_out, c_out, sc_out = [], [], []
        for sid, scored_list in entity_scored.items():
            for sc, cid in scored_list:
                s1_out.append(sid); c_out.append(cid); sc_out.append(sc)
        pl.DataFrame({
            "s1_id": s1_out, "cand_id": c_out, "score": np.array(sc_out, dtype=np.float32)
        }).write_parquet(scores_save_path)
        log.info(f"  Saved {len(s1_out):,} scored pairs.")
        del s1_out, c_out, sc_out

    return apply_threshold_cap(entity_scored, threshold, max_matches_per_entity, n_entities, total_pairs_scored)




# ---------------------------------------------------------------------------
# Submission builder
# ---------------------------------------------------------------------------

def build_matching_results(
    predictions: dict[str, list[str]],
    test_s1_ids: list[str],
) -> pl.DataFrame:
    rows: list[dict] = []
    for s1_id in test_s1_ids:
        matches = predictions.get(s1_id, [])
        seen: set[str] = set()
        deduped: list[str] = []
        for m in matches:
            if m not in seen:
                seen.add(m)
                deduped.append(m)
        rows.append({
            "source1_entity_id": s1_id,
            "matched_entity_ids": ",".join(sorted(deduped)),
        })
    return pl.DataFrame(rows)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--processed-dir", default="dataset/processed")
    parser.add_argument("--candidate-file", default="output/candidate_pairs.tsv")
    parser.add_argument("--model-dir", default="output/models")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--threshold-override", type=float, default=None,
                        help="Override the decision threshold from model_meta.json")
    parser.add_argument("--max-matches-per-entity", type=int, default=5,
                        help="Max candidates to predict per S1 entity (top-K by score). "
                             "Ground truth median=4, max=11. Default 5.")
    parser.add_argument("--entity-batch-size", type=int, default=10_000,
                        help="Entities per inference batch. 10K × ~100 cands = ~1M pairs "
                             "→ ~150 MB numpy RAM. Reduce if OOM.")
    parser.add_argument("--no-country-filter", action="store_true")
    args = parser.parse_args()

    proc_dir = Path(args.processed_dir)
    model_dir = Path(args.model_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with StageTimer("Inference Pipeline"):
        log.info(f"Loading model from [highlight]{model_dir / 'lgbm_model.pkl'}[/highlight] …")
        with open(str(model_dir / "lgbm_model.pkl"), "rb") as f:
            model = pickle.load(f)
        with open(str(model_dir / "model_meta.json")) as f:
            meta = json.load(f)

        threshold = args.threshold_override or meta["threshold"]
        log.info(f"Decision threshold       : [metric]{threshold:.4f}[/metric]")
        log.info(f"Max matches per entity   : [metric]{args.max_matches_per_entity}[/metric]")
        log.info(f"Entity batch size        : [metric]{args.entity_batch_size:,}[/metric]")

        sysinfo(show=True)

        log.info("Loading preprocessed test data …")
        s1_df = pl.read_parquet(str(proc_dir / "test_s1.parquet"))
        s2_df = pl.read_parquet(str(proc_dir / "test_s2.parquet"))
        s3_df = pl.read_parquet(str(proc_dir / "test_s3.parquet"))
        s23_df = pl.concat([s2_df, s3_df])

        test_s1_ids = s1_df["entity_id"].to_list()
        log.info(f"  Test S1 entities: [highlight]{len(test_s1_ids):,}[/highlight]")

        log.info(f"Loading candidates from [highlight]{args.candidate_file}[/highlight] …")
        candidates_df = pl.read_csv(
            args.candidate_file, separator="\t",
            null_values=[""], infer_schema_length=100,
        )

        scores_path = str(out_dir / "scores_raw.parquet")
        predictions = run_inference(
            candidates_df, s1_df, s23_df, model,
            threshold=threshold,
            apply_country_filter=not args.no_country_filter,
            entity_batch_size=args.entity_batch_size,
            max_matches_per_entity=args.max_matches_per_entity,
            scores_save_path=scores_path,
            min_save_threshold=0.40,
        )

        for s1_id in test_s1_ids:
            predictions.setdefault(s1_id, [])

        results_df = build_matching_results(predictions, test_s1_ids)

    out_path = out_dir / "matching_results.tsv"
    results_df.write_csv(str(out_path), separator="\t", quote_style="never")
    log.info(f"Saved → [highlight]{out_path}[/highlight]")

    n_singletons = results_df.filter(pl.col("matched_entity_ids") == "").height
    print_metrics("Submission File Summary", {
        "Total rows":       f"{len(results_df):,}",
        "With matches":     f"{len(results_df) - n_singletons:,}",
        "Singletons":       f"{n_singletons:,}",
        "Output path":      str(out_path),
    })
    print_done("Inference complete — run validate_submission.py to check format!")


if __name__ == "__main__":
    main()
